-- AlterTable
ALTER TABLE `Payment` ADD COLUMN `gateway` VARCHAR(191) NULL,
ADD COLUMN `commissionRate` DOUBLE NOT NULL DEFAULT 0,
ADD COLUMN `commissionAmount` DOUBLE NOT NULL DEFAULT 0,
ADD COLUMN `tutorEarnings` DOUBLE NOT NULL DEFAULT 0;
